import {colors} from './colors';

export const theme = {
  on_primary_light: colors.white,
  primary_light: colors.blue['600'],
  on_surface_light: colors.navy['700'],
  floating_surface_light: colors.white,
  surface_light: colors.white,
  error_light: colors.brown['600'],
  on_change_light: colors.white,
  change_addition_light: colors.green['600'],
  change_removal_light: colors.red['600'],
  change_mixed_light: colors.yellow['600'],
  change_refactored_light: colors.purple['600'],
  ripple_primary_light: colors.blue['600_30'],
  ripple_on_surface_light: colors.navy['700_24'],
  tint_on_surface_16_light: colors.navy['700_16'],
  tint_on_surface_08_light: colors.navy['700_08'],
  tint_primary_20_light: colors.blue['600_20'],
  tint_primary_10_light: colors.blue['600_10'],

  on_primary_dark: colors.black,
  primary_dark: colors.blue['300'],
  on_surface_dark: colors.navy['100'],
  floating_surface_dark: colors.navy['800'],
  surface_dark: colors.navy['900'],
  error_dark: colors.brown['300'],
  on_change_dark: colors.black,
  change_addition_dark: colors.green['300'],
  change_removal_dark: colors.red['300'],
  change_mixed_dark: colors.yellow['300'],
  change_refactored_dark: colors.purple['300'],
  ripple_primary_dark: colors.blue['300_30'],
  ripple_on_surface_dark: colors.navy['100_24'],
  tint_on_surface_16_dark: colors.navy['100_16'],
  tint_on_surface_08_dark: colors.navy['100_08'],
  tint_primary_20_dark: colors.blue['300_20'],
  tint_primary_10_dark: colors.blue['300_10'],
};
