import { colors } from "./colors";

export const color_tokens = {
  on_primary_light: colors.white,
  primary_light: colors.blue["600"],
  label_high_emphasis_light: colors.slate["700"],
  label_medium_emphasis_light: colors.slate["700_64"],
  label_low_emphasis_light: colors.slate["700_32"],
  floating_surface_light: colors.white,
  surface_light: colors.white,
  error_light: colors.pink["600"],
  error_background_light: colors.pink["600_10"],
  on_change_light: colors.white,
  change_addition_light: colors.green["600"],
  change_removal_light: colors.red["600"],
  change_mixed_light: colors.yellow["600"],
  change_refactored_light: colors.purple["600"],
  ripple_primary_light: colors.blue["600_30"],
  ripple_neutral_light: colors.slate["700_24"],
  tint_neutral_01_light: colors.slate["700_16"],
  tint_neutral_02_light: colors.slate["700_08"],
  tint_neutral_03_light: colors.slate["700_04"],
  tint_primary_01_light: colors.blue["600_20"],
  tint_primary_02_light: colors.blue["600_10"],
  tint_primary_03_light: colors.blue["600_05"],

  on_primary_dark: colors.black,
  primary_dark: colors.blue["300"],
  label_high_emphasis_dark: colors.slate["200"],
  label_medium_emphasis_dark: colors.slate["200_64"],
  label_low_emphasis_dark: colors.slate["200_32"],
  floating_surface_dark: colors.slate["800"],
  surface_dark: colors.slate["900"],
  error_dark: colors.pink["300"],
  error_background_dark: colors.pink["300_20"],
  on_change_dark: colors.black,
  change_addition_dark: colors.green["300"],
  change_removal_dark: colors.red["300"],
  change_mixed_dark: colors.yellow["300"],
  change_refactored_dark: colors.purple["300"],
  ripple_primary_dark: colors.blue["300_30"],
  ripple_neutral_dark: colors.slate["200_24"],
  tint_neutral_01_dark: colors.slate["200_16"],
  tint_neutral_02_dark: colors.slate["200_08"],
  tint_neutral_03_dark: colors.slate["200_04"],
  tint_primary_01_dark: colors.blue["300_20"],
  tint_primary_02_dark: colors.blue["300_10"],
  tint_primary_03_dark: colors.blue["300_05"],
};
